on: push
name: CI

jobs:
  build:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm install
